### ISSUE TITLE
dotnet build doesn't build the solution

### ISSUE THREAD

**Issue by isaacabraham** [isaacabraham/safe-lite#2]
The client fails with this error:

```
FSC : error FS0193: The module/namespace 'Encode' from compilation unit 'Thoth.Json' did not contain the val 'ValLinkagePartialKey(generateEncoder)' [C:\Users\isaac\code\safelight\src\Client\Client.fsproj]
```

**Comment by theimowski** [comment]
I've seen that before, not sure if that might be related to Thoth.Json version conflicts.
Anyway is it even possible to build the solution using `dotnet build` ? I mean how would you compile Client?

**Comment by isaacabraham** [comment]
It works for current safe template I believe (maybe I'm wrong!).

**Comment by isaacabraham** [comment]
But then we should have some way of not building the client when you do a dotnet build perhaps
