### ISSUE TITLE
Should we keep node_modules in src\client?

### ISSUE THREAD

**Issue by isaacabraham** [isaacabraham/safe-lite#3]
We could also leave it at the top level. Don't know which is better.

**Comment by CallumVass** [comment]
I think leaving in src/Client is fine because that is where the node modules will be used from.

**Comment by isaacabraham** [comment]
I was thinking from the perspective of doing a restore - you then can't do it from the top level like with paket or nuget. You have to first cd to that client folder. It would be nice if we could do it from the top-level.

**Comment by CallumVass** [comment]
So do you mean to have the package.json folder at the root level and then you can run `npm install` from there?

You already have to cd into the server directory to build/run that project as well. 

Another option is to just have a `build.cmd` file at the root level which will do it all for you (cd into Client and Server, do the restore and run the app)?

**Comment by isaacabraham** [comment]
@theimowski any thoughts?

**Comment by Zaid-Ajaj** [comment]
> Should we keep node_modules in src\client? 

Yes please, keep client-related artifacts in the client

**Comment by isaacabraham** [comment]
@CallumVass yeah, you make some good points. This is a "bare bones" version of the template. For the newcomers, they might prefer to use the "full" template option anyway.

**Comment by isaacabraham** [comment]
@zaid-ajaj for my education, what are the reasons you're thinking of why we should do this?

**Comment by Zaid-Ajaj** [comment]
In my experience, I had to build several front-end "apps" in one application where each had their own package.json to make things easy and simple so I use that by default. That said, since this is the lite version, it is not really a problem

**Comment by isaacabraham** [comment]
that's good enough for me :-)
