### ISSUE TITLE
Client starts on 0.0.0.0 but you need to use localhost

### ISSUE THREAD

**Issue by isaacabraham** [isaacabraham/safe-lite#4]
It's not obvious what the url of the client.

**Comment by theimowski** [comment]
0.0.0.0 has been chosen [for this purpose](https://github.com/fable-compiler/webpack-config-template/commit/34c04e8474e1a6e94698dd1e14e5a197733a65f2) - I would leave it

**Comment by isaacabraham** [comment]
Good point - I'll revert this.
