### ISSUE TITLE
npm build doesn't work

### ISSUE THREAD

**Issue by isaacabraham** [isaacabraham/safe-lite#5]
But it works doing `node_modules\.bin\webpack -p`.

**Comment by CallumVass** [comment]
What error do you get when you run this? 

I was able to run `npm run build` and it created a deploy folder with everything bundled inside it

**Comment by isaacabraham** [comment]
Mmm maybe I was just running `npm webpack-dev-server`. We could also add an entry into the package.json file perhaps?

**Comment by CallumVass** [comment]
There is an `start` script which already calls `webpack-dev-server`:

    "scripts": {
        "start": "webpack-dev-server",
        "build": "webpack -p"
    },

**Comment by isaacabraham** [comment]
Doh
